apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  containers:
  - name: cloud-sdk
    image: gcr.io/google.com/cloudsdktool/cloud-sdk
    imagePullPolicy: Always
    env:  
      - name: CLOUDSDK_CONTAINER_CLUSTER
        value: belgium-01
      - name: CLOUDSDK_COMPUTE_ZONE
        value: europe-west1-d
    command:
      - sleep
    args:   
      - infinity
  - name: docker
    image: docker:20.10.12-alpine3.15       
    imagePullPolicy: IfNotPresent
    command:         
      - sleep        
    args: 
      - infinity
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock # We use the k8s host docker engine
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
